# Use the official Airflow image as the base image
FROM python:3.10.15-bullseye
ENV AIRFLOW_HOME=/opt/airflow
USER root
RUN apt-get update && \
    apt-get install -y ffmpeg && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
# Install any additional Python dependencies for Airflow here
# Example:
# RUN pip install <additional-package>
RUN pip install apache-airflow
RUN pip install psycopg2 opencv-python tqdm streamlink


